const WORD_EMOJIS: Record<string, string> = {
  abundant: '🌊',
  acknowledge: '🤝',
  acquire: '🎯',
  adequate: '✅',
  assess: '📋',
  assume: '🤔',
  contribute: '🤲',
  crucial: '⚡',
  decline: '📉',
  distinct: '🔍',
  emphasize: '💡',
  enhance: '✨',
  establish: '🏗️',
  generate: '⚙️',
  hypothesis: '🧪',
  accomplish: '🏆',
  appreciate: '💝',
  awkward: '😅',
  convince: '🎤',
  essential: '💎',
  genuine: '💯',
  inevitable: '🌀',
  negotiate: '🤝',
  overcome: '💪',
  pursue: '🏃',
  analyze: '🔬',
  benefit: '🎁',
  challenge: '🧗',
  demonstrate: '📊',
  environment: '🌿',
  evaluate: '⚖️',
  flexible: '🤸',
  impact: '💥',
  innovation: '🚀',
  maintain: '🔧',
  perspective: '👁️',
  significant: '📌',
  strategy: '♟️',
  substantial: '🏔️',
  sustainable: '♻️',
  comprehensive: '📚',
  preliminary: '📝',
  sufficient: '👍',
  accurate: '🎯',
  ambiguous: '🌫️',
  bias: '⚖️',
  coherent: '🧩',
  controversial: '🔥',
  credible: '🛡️',
  elaborate: '🎨',
  feasible: '✅',
  fluctuate: '📈',
  implement: '🔨',
  implication: '🔗',
  integrate: '🧬',
  modify: '🔄',
  phenomenon: '🌟',
  prohibit: '🚫',
  relevant: '🎯',
  reluctant: '😬',
  resolve: '🔑',
  restrict: '🚧',
  revolutionize: '💫',
  stimulate: '⚡',
  transparent: '🪟',
  vulnerable: '🛡️',
  widespread: '🌍',
  important: '⭐',
  different: '🔀',
  possible: '🌈',
  popular: '👑',
  reason: '💭',
  similar: '👯',
  provide: '📦',
  increase: '📈',
  situation: '🗺️',
  require: '📋',
  advantage: '🏅',
  affect: '🎭',
  opportunity: '🚪',
  develop: '🌱',
  research: '🔬',
  influence: '🧲',
  economy: '💰',
  community: '🏘️',
  compelling: '🧲',
  deteriorate: '📉',
  exacerbate: '🔥',
  inherent: '🧬',
  mitigate: '🛡️',
  paradox: '🔮',
  unprecedented: '🆕',
  proliferate: '🌿',
  scrutinize: '🔍',
  counterpart: '🤝',
  corroborate: '✅',
  nevertheless: '↩️',
  predominantly: '📊',
};

export function getWordEmoji(word: string): string {
  const key = word.toLowerCase();
  return WORD_EMOJIS[key] || getDefaultEmoji(key);
}

function getDefaultEmoji(word: string): string {
  const firstChar = word.charCodeAt(0);
  const emojis = ['📖', '🌟', '💡', '🎓', '📝', '🔤', '✏️', '📚', '🗂️', '🧠'];
  return emojis[firstChar % emojis.length];
}
